/// <reference types="tree-sitter-cli/dsl" />
// @ts-check
// Auto-generated by Almide grammar generator (written in Almide)
// Do not edit manually — edit generator/almide_grammar.almd instead

module.exports = grammar({
  name: "almide",

  extras: ($) => [/\s/, $.line_comment, $.block_comment],

  word: ($) => $.identifier,

  conflicts: ($) => [
    [$._type_body, $._type_expr],
    [$.expression_statement, $.block_expression],
    [$.record_expression, $.block_expression],
    [$.expression, $.range_expression],
  ],

  rules: {
    source_file: ($) => seq(optional($.module_declaration), repeat($.import_declaration), repeat($._top_declaration)),

    module_declaration: ($) => seq("module", $.identifier),

    import_declaration: ($) => seq("import", $.import_path, optional(seq("as", $.identifier))),

    import_path: ($) => seq($.identifier, repeat(seq(".", $.identifier))),

    _top_declaration: ($) => choice($.function_declaration, $.type_declaration, $.trait_declaration, $.impl_declaration, $.test_declaration),

    function_declaration: ($) => seq(optional($.visibility_modifier), optional("async"), optional("effect"), "fn", $.function_name, optional($.generic_params), $.parameter_list, "->", $._type_expr, "=", $.expression),

    visibility_modifier: ($) => choice("pub", "mod", "local"),

    function_name: ($) => choice($.identifier, $.predicate_identifier),

    predicate_identifier: ($) => /[a-z_][a-zA-Z0-9_]*\?/,

    parameter_list: ($) => seq("(", optional(seq($.parameter, repeat(seq(",", $.parameter)))), ")"),

    parameter: ($) => seq($.identifier, ":", $._type_expr),

    type_declaration: ($) => seq("type", $.type_name, optional($.generic_params), "=", $._type_body),

    _type_body: ($) => seq(choice($.record_type, $.variant_type, $.newtype, $._type_expr), optional($.deriving_clause)),

    record_type: ($) => seq("{", optional(seq($.field_type, repeat(seq(",", $.field_type)))), optional(","), "}"),

    field_type: ($) => seq($.identifier, ":", $._type_expr),

    variant_type: ($) => seq("|", $.variant_case, repeat(seq("|", $.variant_case))),

    variant_case: ($) => seq($.type_name, optional(choice(seq("(", seq($._type_expr, repeat(seq(",", $._type_expr))), ")"), seq("{", seq($.field_type, repeat(seq(",", $.field_type))), "}")))),

    newtype: ($) => seq("newtype", $._type_expr),

    deriving_clause: ($) => seq("deriving", seq($.type_name, repeat(seq(",", $.type_name)))),

    generic_params: ($) => seq("[", seq($.type_param, repeat(seq(",", $.type_param))), "]"),

    type_param: ($) => seq($.type_name, optional(seq(":", $.trait_bound))),

    trait_bound: ($) => seq($.type_name, repeat(seq("+", $.type_name))),

    _type_expr: ($) => choice($.type_name, $.generic_type, $.function_type, $.record_type, $.tuple_type, $.unit_type),

    generic_type: ($) => seq($.type_name, "[", seq($._type_expr, repeat(seq(",", $._type_expr))), "]"),

    function_type: ($) => seq("fn", "(", optional(seq($._type_expr, repeat(seq(",", $._type_expr)))), ")", "->", $._type_expr),

    tuple_type: ($) => seq("(", $._type_expr, ",", seq($._type_expr, repeat(seq(",", $._type_expr))), ")"),

    unit_type: ($) => seq("(", ")"),

    trait_declaration: ($) => seq("trait", $.type_name, optional($.generic_params), "{", repeat($.trait_method), "}"),

    trait_method: ($) => seq(optional("effect"), "fn", $.function_name, optional($.generic_params), $.parameter_list, "->", $._type_expr),

    impl_declaration: ($) => seq("impl", $.type_name, optional($.generic_params), "for", $._type_expr, "{", repeat($.function_declaration), "}"),

    test_declaration: ($) => seq("test", $.string_literal, $.block_expression),

    _statement: ($) => choice($.let_statement, $.var_statement, $.assignment_statement, $.expression_statement),

    let_statement: ($) => choice(seq("let", $.identifier, optional(seq(":", $._type_expr)), "=", $.expression), seq("let", "{", seq($.identifier, repeat(seq(",", $.identifier))), "}", "=", $.expression)),

    var_statement: ($) => seq("var", $.identifier, optional(seq(":", $._type_expr)), "=", $.expression),

    assignment_statement: ($) => seq($.identifier, "=", $.expression),

    expression_statement: ($) => $.expression,

    expression: ($) => choice($.binary_expression, $.unary_expression, $.pipe_expression, $.primary_expression),

    primary_expression: ($) => choice($.integer_literal, $.float_literal, $.string_literal, $.heredoc_string, $.boolean_literal, $.unit_expression, $.identifier, $.predicate_identifier, $.type_name, $.list_expression, $.map_expression, $.record_expression, $.tuple_expression, $.call_expression, $.member_expression, $.tuple_index_expression, $.index_expression, $.if_expression, $.match_expression, $.block_expression, $.do_expression, $.for_in_expression, $.lambda_expression, $.try_expression, $.await_expression, $.range_expression, $.some_expression, $.none_expression, $.ok_expression, $.err_expression, $.hole_expression, $.todo_expression, $.parenthesized_expression),

    integer_literal: ($) => /[0-9]+/,

    float_literal: ($) => /[0-9]+\.[0-9]+/,

    string_literal: ($) => choice(seq("\"", repeat(choice($.escape_sequence, $.string_interpolation, $.string_content)), "\""), $.raw_string),

    string_content: ($) => /[^"\\$]+|\$/,

    raw_string: ($) => token(seq("r\"", /[^"]*/, "\"")),

    string_interpolation: ($) => seq("${", $.expression, "}"),

    heredoc_string: ($) => token(choice(seq("\"\"\"", /([^"]|"[^"]|""[^"])*/, "\"\"\""), seq("r\"\"\"", /([^"]|"[^"]|""[^"])*/, "\"\"\""))),

    escape_sequence: ($) => /\\[nrt\\"$]/,

    boolean_literal: ($) => choice("true", "false"),

    unit_expression: ($) => prec(1, seq("(", ")")),

    list_expression: ($) => seq("[", optional(seq($.expression, repeat(seq(",", $.expression)))), optional(","), "]"),

    map_expression: ($) => choice(seq("[", ":", "]"), seq("[", seq($.map_entry, repeat(seq(",", $.map_entry))), optional(","), "]")),

    map_entry: ($) => seq(field("key", $.expression), ":", field("value", $.expression)),

    record_expression: ($) => seq("{", optional($.spread_field), optional(seq($.record_field, repeat(seq(",", $.record_field)))), optional(","), "}"),

    record_field: ($) => seq($.identifier, ":", $.expression),

    spread_field: ($) => seq("...", $.expression, ","),

    tuple_expression: ($) => seq("(", $.expression, ",", seq($.expression, repeat(seq(",", $.expression))), ")"),

    call_expression: ($) => prec.left(9, seq(choice($.identifier, $.predicate_identifier, $.type_name, $.member_expression), $.argument_list)),

    argument_list: ($) => seq("(", optional(seq($.argument, repeat(seq(",", $.argument)))), ")"),

    argument: ($) => choice(seq($.identifier, ":", $.expression), $.expression),

    member_expression: ($) => prec.left(8, seq(choice($.primary_expression), ".", choice($.identifier, $.predicate_identifier))),

    tuple_index_expression: ($) => prec.left(8, seq($.primary_expression, ".", $.integer_literal)),

    index_expression: ($) => prec.left(8, seq($.primary_expression, "[", $.expression, "]")),

    binary_expression: ($) => choice(prec.left(2, seq(field("left", $.expression), field("operator", "or"), field("right", $.expression))), prec.left(3, seq(field("left", $.expression), field("operator", "and"), field("right", $.expression))), prec.left(4, seq(field("left", $.expression), field("operator", "=="), field("right", $.expression))), prec.left(4, seq(field("left", $.expression), field("operator", "!="), field("right", $.expression))), prec.left(4, seq(field("left", $.expression), field("operator", "<"), field("right", $.expression))), prec.left(4, seq(field("left", $.expression), field("operator", ">"), field("right", $.expression))), prec.left(4, seq(field("left", $.expression), field("operator", "<="), field("right", $.expression))), prec.left(4, seq(field("left", $.expression), field("operator", ">="), field("right", $.expression))), prec.left(5, seq(field("left", $.expression), field("operator", "+"), field("right", $.expression))), prec.left(5, seq(field("left", $.expression), field("operator", "-"), field("right", $.expression))), prec.left(5, seq(field("left", $.expression), field("operator", "++"), field("right", $.expression))), prec.left(6, seq(field("left", $.expression), field("operator", "*"), field("right", $.expression))), prec.left(6, seq(field("left", $.expression), field("operator", "/"), field("right", $.expression))), prec.left(6, seq(field("left", $.expression), field("operator", "%"), field("right", $.expression))), prec.left(6, seq(field("left", $.expression), field("operator", "^"), field("right", $.expression)))),

    unary_expression: ($) => prec(7, seq(field("operator", choice("not", "-")), field("operand", $.expression))),

    pipe_expression: ($) => prec.right(1, seq(field("left", $.expression), "|>", field("right", $.expression))),

    if_expression: ($) => seq("if", field("condition", $.expression), "then", field("consequence", $.expression), "else", field("alternative", $.expression)),

    match_expression: ($) => seq("match", field("value", $.expression), "{", seq($.match_arm, repeat(seq(",", $.match_arm))), optional(","), "}"),

    match_arm: ($) => seq(field("pattern", $.pattern), optional(seq("if", field("guard", $.expression))), "=>", field("body", $.expression)),

    block_expression: ($) => seq("{", repeat($._statement), optional($.expression), "}"),

    do_expression: ($) => seq("do", $.block_expression),

    for_in_expression: ($) => seq("for", choice($.identifier, seq("(", $.identifier, ",", $.identifier, ")")), "in", $.expression, $.block_expression),

    guard_expression: ($) => seq("guard", $.expression, "else", $.expression),

    lambda_expression: ($) => seq("fn", "(", optional(seq($.lambda_param, repeat(seq(",", $.lambda_param)))), ")", "=>", $.expression),

    lambda_param: ($) => choice(seq($.identifier, ":", $._type_expr), $.identifier),

    some_expression: ($) => seq("some", "(", $.expression, ")"),

    none_expression: ($) => "none",

    ok_expression: ($) => seq("ok", "(", $.expression, ")"),

    err_expression: ($) => seq("err", "(", $.expression, ")"),

    try_expression: ($) => seq("try", $.expression),

    await_expression: ($) => seq("await", $.expression),

    hole_expression: ($) => "_",

    todo_expression: ($) => seq("todo", "(", optional($.string_literal), ")"),

    range_expression: ($) => prec.left(0, seq($.primary_expression, choice("..", "..="), $.primary_expression)),

    parenthesized_expression: ($) => seq("(", $.expression, ")"),

    pattern: ($) => choice($.wildcard_pattern, $.literal_pattern, $.identifier_pattern, $.some_pattern, $.none_pattern, $.ok_pattern, $.err_pattern, $.constructor_pattern, $.record_pattern, $.tuple_pattern),

    wildcard_pattern: ($) => "_",

    identifier_pattern: ($) => $.identifier,

    literal_pattern: ($) => choice($.integer_literal, $.float_literal, $.string_literal, $.boolean_literal),

    some_pattern: ($) => seq("some", "(", $.pattern, ")"),

    none_pattern: ($) => "none",

    ok_pattern: ($) => seq("ok", "(", $.pattern, ")"),

    err_pattern: ($) => seq("err", "(", $.pattern, ")"),

    constructor_pattern: ($) => seq($.type_name, "(", optional(seq($.pattern, repeat(seq(",", $.pattern)))), ")"),

    record_pattern: ($) => seq("{", seq($.identifier, repeat(seq(",", $.identifier))), "}"),

    tuple_pattern: ($) => seq("(", $.pattern, ",", seq($.pattern, repeat(seq(",", $.pattern))), ")"),

    line_comment: ($) => /\/\/[^\n]*/,

    block_comment: ($) => token(seq("(*", /([^*]|\*[^)])*/, "*)")),

    identifier: ($) => /[a-z_][a-zA-Z0-9_]*/,

    type_name: ($) => /[A-Z][a-zA-Z0-9]*/
  },
});
